defaults: &defaults
  distance_coefficient:  0.51080610
  crime_rating_coefficient: 0.00025608
  gradient_coefficient: 0.00000225

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
