default: &default
  adapter: postgresql
  encoding: unicode
  pool: 15
  host: localhost

development:
  <<: *default
  database: streetwise_development

test:
  <<: *default
  database: streetwise_test

production:
  <<: *default
  database: streetwise_production
