# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee0e1b7ab512add80d7ac1e4e03ac5314a7e474a5e02f8d8d3735f7b685433a771315bb0b99a5eb589795432e2b1b1429c3e21e9dde337a15588e347e5b3b87d

test:
  secret_key_base: 3dffe21ad4f51d60e10b09bcb84230a0fd2f35c895e1819875da7592ad07c509cc267fed177eeab68499a0409a4edaa6d7493dd356657640d5e17f9b17fdc4ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
